### PR TITLE
sample for enabling speech in the web chat control

### PR DESCRIPTION
**Pull request by DeniseMak**
This is a sample that demonstrates a speech-enabled Web Chat control, to reference from documentation. This sample gets the botchat.css, botchat.js and CognitiveServices.js files from the Bot Framework CDN, so you can use it to talk to your bot without having to build these files yourself.

### CODE REVIEW

**Comment by cheahheng** [comment]
Hi, for speech recognition using CRIS, which option should I use? I tried Option 4, entered the keys, westus link and modified the CognitiveServices.js to reflect the same but it doesn't work.

**Comment by DeniseMak** [comment]
Hi @cheahheng - Can you provide more detail on how you are calling CRIS? If you're building a custom implementation you may want to use Option 5, which is like this:
```
//  Option 5: Your own custom implementations of ISpeechRecognizer and ISpeechSynthesizer
     const speechOptions = {
          speechRecognizer: new YourOwnSpeechRecognizer(),
          speechSynthesizer: new YourOwnSpeechSynthesizer()
     };
```

**Comment by cheahheng** [comment]
Hi Denise, CRIS provides a websocket endpoint that I can use to access the custom language model. I was thinking if I could just make use of the CognitiveServices.js and make changes to the connection to minimize the effort.

Do you have an example of using Option 5?

**Comment by DeniseMak** [comment]
I did some research and found that Web Chat uses the SpeechToText-WebSockets-Javascript<https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript> library for speech recognition which is targeted toward Cognitive Services Speech recognition and doesn’t support the Custom Speech Service (CRIS) at this time.

**Comment by cheahheng** [comment]
Hey Denise, I know about the SpeechToText-WebSockets js and have manage to consume CRIS. They do support it.
But with chat bot, there's some difficulty in using it to consume CRIS.

**Comment by DeniseMak** [comment]
@shahidkhuram  Can you comment on the difficulty of using CRIS within a Bot Framework bot? Is there any workaround, or is it just a matter of support that will be added at a later date?

**Comment by shahidkhuram** [comment]
It looks like webchat is using an older version of that speech library. @cheahheng  could you please try updating the webchat to point to the latest version of the speech JS lib to see if that resolves the problem?

**Comment by cheahheng** [comment]
Hi Shahid, do you mean updating the CognitiveServices.js? where is the latest version of the speech JS lib? residing?

**Comment by cheahheng** [comment]
Hi Denise, I manage to consume CRIS and everything works fine. I need another help, do you know how to enable the mic 1 time and have the conversation with the bot without needing to keep pressing the mic each time we need to input speech?

**Comment by DeniseMak** [comment]
@cheahheng - Can you tell me which version of the speech JS lib you used to get CRIS working? I'd like to update the doc to point that out.

To enable the mic automatically, you can set `inputHint` to `expectingInput` in the bot code. 

**Node.js**
```javascript
builder.Prompts.text(session, 'This is the text that will be displayed.', {                                    
    speak: 'This is the text that will be spoken initially.',
    retrySpeak: 'This is the text that is spoken after waiting a while for user input.',  
    inputHint: builder.InputHint.expectingInput
});
```
**C#**
```cs
Activity reply = activity.CreateReply("This is the text that will be displayed."); 
reply.Speak = "This is the text that will be spoken.";
reply.InputHint = InputHints.ExpectingInput;
```
The help topics about setting the microphone state for are here:
* Node.js: https://docs.microsoft.com/en-us/bot-framework/nodejs/bot-builder-nodejs-send-input-hints
* C#: https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-add-input-hints

**Comment by cheahheng** [comment]
@DeniseMak can you point me to the file that I should modify per your suggestion? I'm using the BotFramework-WebChat examples here...

**Comment by DeniseMak** [comment]
The C# and Node.js code above would be in your bot code, not in the Web Chat control.

**Comment by cheahheng** [comment]
@DeniseMak I did the change here at the bot connector within the bot code itself and it works. Thanks!

        if (msg.type === 'message' && !msg.inputHint) {
            msg.inputHint = lastMsg ? 'expectingInput' : 'ignoringInput';

**Pull request merged**
